### ISSUE TITLE
Unicode Cookies Break CherryPy

### ISSUE THREAD

**Issue by serac** [OpenIDC/pyoidc#186]
It appears that b1953a1d7cae2168312f7a76ec440258c8d08dc3 and related commits create unicode headers, which appears to break cherrypy on Python 2.7:

```
WSGI response header key u'Set-Cookie' is not of type str.
['Traceback (most recent call last):\n', '  File "/Users/marvin/Documents/Develop/pyoidc-op/src/server.py", line 374, in application\n    return callback(environ, start_response, logger)\n', '  File "/Users/marvin/Code/pyoidc/src/oic/oauth2/provider.py", line 66, in __call__\n    return self.func(*args, **kwargs)\n', '  File "/Users/marvin/Documents/Develop/pyoidc-op/src/server.py", line 172, in authorization\n    logger=logger)\n', '  File "/Users/marvin/Code/pyoidc/src/oic/utils/http_util.py", line 380, in wsgi_wrapper\n    return resp(environ, start_response)\n', '  File "/Users/marvin/Code/pyoidc/src/oic/utils/http_util.py", line 114, in __call__\n    start_response(self.status, self.headers)\n', '  File "/Library/Python/2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2173, in start_response\n    raise TypeError("WSGI response header key %r is not of type str." % k)\n', "TypeError: WSGI response header key u'Set-Cookie' is not of type str.\n"]
AssertionError('WSGI start_response called a second time with no exc_info.',)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
    req.respond()
  File "/Library/Python/2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
    self.server.gateway(self).respond()
  File "/Library/Python/2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2135, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/Users/marvin/Documents/Develop/pyoidc-op/src/server.py", line 381, in application
    return resp(environ, start_response)
  File "/Users/marvin/Code/pyoidc/src/oic/utils/http_util.py", line 49, in __call__
    start_response(self.status, self.headers)
  File "/Library/Python/2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2157, in start_response
    raise AssertionError("WSGI start_response called a second "
AssertionError: WSGI start_response called a second time with no exc_info
```

The double invocation of start_response is an artifact of the error handling (which may be a separate bug), but the root cause is the type of cookie header/values. The cherrypy code reference that enforces str type is here:

https://bitbucket.org/cherrypy/cherrypy/src/ea07b29deabd28d5a10b764a1a452c876692d028/cherrypy/wsgiserver/wsgiserver2.py?at=default&fileviewer=file-view-default#wsgiserver2.py-2283

HTTP protocol headers are defined to contain exclusively ASCII characters [1], so the cherrypy check may be correct from a strict viewpoint (at least for python 2.7 where unicode data is a separate type).

[1] https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2

**Comment by serac** [comment]
Pull request #187 fixes problem for me.

**Comment by tpazderka** [comment]
Looks like fixed, so closing. Please reopen otherwise.
