### ISSUE TITLE
"AttributeError: 'newstr' object has no attribute 'items'

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#315]
I'm running examples op2 and rp3. 
When I submit a correct username and password, I get the following error (on terminal): 

```
'Traceback (most recent call last):\n', ' 
File "./server.py", line 347, in application\n    return callback(environ, start_response)\n', '
File "./server.py", line 237, in authorization\n    self.oas.authorization_endpoint, logger=logger)\n', ' 
File "/Users/vahid/pyProjects/pyoidc/src/oic/utils/http_util.py", line 411, in wsgi_wrapper\n    args = func(**kwargs)\n', '
File "/Users/vahid/pyProjects/pyoidc/src/oic/oic/provider.py", line 773, in authorization_endpoint\n    return self.authz_part2(authnres["user"], areq, sid, cookie=cookie)\n', '
File "/Users/vahid/pyProjects/pyoidc/src/oic/oic/provider.py", line 776, in authz_part2\n    result = self._complete_authz(user, areq, sid, **kwargs)\n', ' 
File "/Users/vahid/pyProjects/pyoidc/src/oic/oauth2/provider.py", line 724, in _complete_authz\n    _c.load(_kaka)\n', '
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load\n    for k, v in rawdata.items():\n', '
File "/Users/vahid/vens/pyoidc/lib/python2.7/site-packages/future/types/newstr.py", line 331, in __getattribute__\n    return super(newstr, self).__getattribute__(name)\n', "AttributeError: 'newstr' object has no attribute 'items'\n"
```
I traced the call. It seems at `pyoidc/src/oidc/oauth2/provider.py`, and at line 707, `"cookie"` is expected:
`_kaka = kwargs["cookie"]`

but `kwargs` has only 'logger': 
`return wsgi_wrapper(environ, start_response, self.oas.authorization_endpoint, logger=logger)`

**Comment by lwm** [comment]
Please see https://github.com/OpenIDC/pyoidc#examples for more information. If you have a fix for this, it would be really appreciated. Otherwise, we'll try and release working examples soon.

**Comment by VJalili** [comment]
[This](https://github.com/OpenIDC/pyoidc/pull/317) solves my issue.

**Comment by rajeceind** [comment]
After fixing this issue 

> 'newstr'object has no attribute 'items'

 Now i am getting error like 

> 'error_description': u'Failed to verify client due to: String or Integer object expected for key, unicode found', 'error': u'unauthorized_client'

Log output:

> 2017-04-21 18:19:10,136 oic.utils.authn.client:DEBUG REQ: {u'code': '<REDACTED>', u'state': u'sxsBpa1cUHyPIw9cQ4g5pKhcBc3fKdif', u'redirect_uri': u'https://localhost:8088/authz_cb', u'client_id': u'xyPsi1y5GyB8', u'scope': u'openid profile email address phone', 'grant_type': u'authorization_code'}
> 2017-04-21 18:19:10,136 oic.utils.authn.client:DEBUG Basic auth
> 2017-04-21 18:19:10,137 oic.oic.provider:ERROR Failed to verify client due to: String or Integer object expected for key, unicode found
> 2017-04-21 18:19:10,137 oic.oic.provider:ERROR No client_id, authentication failed

**Comment by VJalili** [comment]
I think you're getting the error because of your python version. Pyoidc is mainly written for python 3.x, and it has issues such as the one you mentioned when running in python 2.x. Unfortunately, python 3.x is not quite backward compatible; and the reason for your error is in the differences between python 3.x and 2.x internal representation of strings (ascii vs. unicode). 

This fix is on the "todo" list: https://github.com/OpenIDC/pyoidc/pull/343

Meanwhile you might be able to fix the issue by upgrading to python 3.x if possible for your application.

**Comment by tpazderka** [comment]
This looks like fixed judging by the comments. If not, please reopen.
