### ISSUE TITLE
get_verify_key return only sig usage keys

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#475]
Method: https://github.com/OpenIDC/pyoidc/blob/aee1bd0933a70dbfd9a8244ad3ad88506bcf16dc/src/oic/utils/keyio.py#L577

Implementation 'get':https://github.com/OpenIDC/pyoidc/blob/aee1bd0933a70dbfd9a8244ad3ad88506bcf16dc/src/oic/utils/keyio.py#L497-L510

So then i deactivate a key, i cant verify access_token.
I get error like:
jwkest.jws.NoSuitableSigningKeys: No key with kid:  here kid of 'ver' key

It's normal behavior?

**Comment by schlenk** [comment]
Do you have the full traceback? How did you deactivate the key?

The code has an explicit clause for key_use='ver' and inactive keys in line 540 of keyio.py, so it should return an inactive key for that key usage.

**Comment by ermakoves** [comment]
traceback:
Traceback (most recent call last):
  File "D:\AAC_ENV\lib\site-packages\tornado-4.4.2-py3.6-win32.egg\tornado\web.py", line 1469, in _execute
    result = yield result
  File "D:\AAC_ENV\lib\site-packages\tornado-4.4.2-py3.6-win32.egg\tornado\gen.py", line 1015, in run
    value = future.result()
  File "D:\AAC_ENV\lib\site-packages\tornado-4.4.2-py3.6-win32.egg\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "D:\AAC_ENV\lib\site-packages\tornado-4.4.2-py3.6-win32.egg\tornado\gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "<string>", line 6, in _wrap_awaitable
  File "D:/SVN_PROJECTS/AFL_SITE/AFL_AAC\handlers\oidc.py", line 318, in get
    response, response_info = await self.application.oidcp.endsession_endpoint(self.request.query, **params)
  File "D:/SVN_PROJECTS/AFL_SITE/AFL_AAC\provider\oidc.py", line 968, in endsession_endpoint
    return await self.end_session_endpoint(request, **kwargs)
  File "D:/SVN_PROJECTS/AFL_SITE/AFL_AAC\provider\oidc.py", line 989, in end_session_endpoint
    uid = self._get_sub_from_id_token(esr['id_token_hint'])
  File "D:/SVN_PROJECTS/AFL_SITE/AFL_AAC\provider\oidc.py", line 1050, in _get_sub_from_id_token
    id_token_hint = OpenIDRequest().from_jwt(token, keyjar=self.keyjar, verify=True)
  File "D:\AAC_ENV\lib\site-packages\oic\oauth2\message.py", line 705, in from_jwt
    _jw.verify_compact(txt, key)
  File "D:\AAC_ENV\lib\site-packages\jwkest\jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "D:\AAC_ENV\lib\site-packages\jwkest\jws.py", line 565, in verify_compact_verbose
    "No key with kid: %s" % (self["kid"]))
jwkest.jws.NoSuitableSigningKeys: No key with kid: j8Ag9oSPvXMTD2FuB-PyvHPh97OBo_7lyhHlg5ixVds

**Comment by ermakoves** [comment]
>  How did you deactivate the key?
Set for key inactive_since=1 and use='ver'

**Comment by schlenk** [comment]
Agreed. Yes, the check behind the 'or' is wrong.

**Comment by tpazderka** [comment]
I think that the `ver` needs to be passed and not replaced by `sig` on line 509.

**Comment by ermakoves** [comment]
> I think that the ver needs to be passed and not replaced by sig on line 509.

Nope, you can have token signed by `sig` key - active or already unactive key - `ver`. So use collections for checking

**Comment by tpazderka** [comment]
Ah, you are right!

**Comment by ermakoves** [comment]
I had repeat that error.
Just test it on keys bundle like ['sig', 'ver']
Update test
`

def test_get_inactive_ver(self):

        ks = KeyJar()
        ks['http://example.com'] = KeyBundle([{"kty": "oct", "key": "a1b2c3d4", "use": "sig"},
                                              {"kty": "oct", "key": "a1b2c3d4", "use": "ver"}])
        ks['http://example.com'][0]._keys[1].inactive_since = 1
        key = ks.get_verify_key(owner='http://example.com')

        assert len(key) == 2
`
