### ISSUE TITLE
distributed claims verification

### ISSUE THREAD

**Issue by zandbelt** [OpenIDC/pyoidc#492]
Pyoidc seems to have incomplete support for handing distributed claims (http://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims). 

When verifying the JWT returned from the distributed claim endpoint it will try and use the key material from the "main" Provider. Instead it should:
  a) get the key material for the Provider that actually generated the JWT using Discovery with the `iss` value, or
  b) it should omit verification since the JWT is obtained from a TLS protected endpoint
Admittedly the spec is not clear on the verification part but the current implementation is broken since the wrong key material is used.

```
2017-12-05 10:11:08,200 otest.aus.tool:ERROR [UserInfo] ExcList: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.2-py3.5.egg/otest/aus/tool.py", line 86, in run_flow
    resp = _oper()
  File "/usr/local/lib/python3.5/dist-packages/otest-0.7.2-py3.5.egg/otest/operation.py", line 105, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/op/oper.py", line 322, in run
    user_info = self.conv.entity.fetch_distributed_claims(user_info)
  File "/usr/local/lib/python3.5/dist-packages/oic-0.12.0-py3.5.egg/oic/oic/__init__.py", line 1071, in fetch_distributed_claims
    userinfo_endpoint=spec["endpoint"])
  File "/usr/local/lib/python3.5/dist-packages/oidctest-0.7.0-py3.5.egg/oidctest/op/client.py", line 104, in do_user_info_request
    sender=self.provider_info["issuer"])
  File "/usr/local/lib/python3.5/dist-packages/oic-0.12.0-py3.5.egg/oic/oauth2/message.py", line 699, in from_jwt
    _jw.verify_compact(txt, key)
  File "/usr/local/lib/python3.5/dist-packages/pyjwkest-1.4.0-py3.5.egg/jwkest/jws.py", line 517, in verify_compact
    return self.verify_compact_verbose(jws, keys, allow_none, sigalg)['msg']
  File "/usr/local/lib/python3.5/dist-packages/pyjwkest-1.4.0-py3.5.egg/jwkest/jws.py", line 588, in verify_compact_verbose
    raise BadSignature()
jwkest.BadSignature
```

**Comment by tpazderka** [comment]
On another look, this is an issue with `jwkest`. So it should be solved there.

Another possibility is to swith to another JWK implementation...

**Comment by tpazderka** [comment]
Ah, never mind... It is in pyoidc, we have to prefetch the keys and pass the correct issuer to the `do_user_info_request` method...
