### ISSUE TITLE
Docker example ,500 error, _cprequest.py, line 656

### ISSUE THREAD

**Issue by bebenekrobert** [OpenIDC/pyoidc#509]
'Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
   response.body = self.handler()
 File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
   self.body = self.oldhandler(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
   return self.callable(*self.args, **self.kwargs)
 File "src/rp.py", line 97, in authenticate
   self.rp.register_with_dynamic_provider(cherrypy.session, uid)
 File "src/rp.py", line 24, in register_with_dynamic_provider
   issuer_url = session["client"].wf.discovery_query(uid)
 File "/usr/local/lib/python2.7/dist-packages/oic/utils/webfinger.py", line 282, in discovery_query
   rsp = self.httpd.http_request(url)
 File "/usr/local/lib/python2.7/dist-packages/oic/oauth2/base.py", line 49, in http_request
   r = requests.request(method, url, **_kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
   return session.request(method=method, url=url, **kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
   resp = self.send(prep, **send_kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
   r = adapter.send(request, **kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
   raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='localhost', port=8093): Max retries exceeded with url: /.well-known/webfinger?resource=https%3A%2F%2Fusername%40localhost%3A8093&rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer (Caused by <class 'socket.error'>: [Errno 99] Cannot assign requested address)'

example from readthedocs: http://pyoidc.readthedocs.io/en/latest/examples/docker.html#

Both containers are runing
I visited localhost:8666
After input: username@localhost:8093 I have  got error 500

**Comment by iammarco11** [comment]
Is this issue fixed?

**Comment by bebenekrobert** [comment]
Probably incorect e-mail
I did not start support ticket on github

**Comment by iammarco11** [comment]
@bebenekrobert any idea on how to run the docker script successfully? what should be the correct UID, username and password? Another query, is there some public forum or community chat or mailing list?
