### ISSUE TITLE
[Help] Unable to decode JWT

### ISSUE THREAD

**Issue by akhilputhiry** [OpenIDC/pyoidc#550]
I am trying to use [Keycloak](https://github.com/keycloak/keycloak) using `oic`

I am getting the following error, 

```
202.54.41.61 - - [19/Jun/2018 13:48:38] "GET / HTTP/1.1" 200 -
202.54.41.61 - - [19/Jun/2018 13:48:45] "GET /openid-login HTTP/1.1" 302 -
[2018-06-19 13:48:46,222] ERROR in app: Exception on /openid-callback [GET]
Traceback (most recent call last):
  File "/home/akhil/client/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akhil/client/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akhil/client/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akhil/client/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akhil/client/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 39, in redirect_uri
    key=[RSAKey(kid="Wue1jxX9Ln8gkfTVZz4ey5tl4U6vNVVIF8-c91pSV9k", use="dec", alg="RS256", key=key)])
  File "/home/akhil/client/env/lib/python2.7/site-packages/jwkest/jwk.py", line 414, in __init__
    self._split()
  File "/home/akhil/client/env/lib/python2.7/site-packages/jwkest/jwk.py", line 483, in _split
    self.n = self.key.n
AttributeError: 'str' object has no attribute 'n'
202.54.41.61 - - [19/Jun/2018 13:48:46] "GET /openid-callback?state=g5TctQVHxFVMzO0D&session_state=0c574335-6f51-4805-b5ab-ba5c1c64643d&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..DedwvHOVOAQwpyP1DAJ4eg.IgrjD-NsL5zPetjGkoKstAulGunDCQhaU-BdiKpGU-2dkPWqsK1xuJJtV5LObK_YUCgtsuoQcgHL3I_-Yv3PuuDV32EFBFXkzoD-Citrsxjo3esD5bwykEAnElgycarb3Glaa42GtlJV3qxoAx-gd9iG3KdsR4oWsV55PzC3MUnSXiG07IUY8IfJrVeN9KVhh9CQhqDo2YT1YtMdBvRN5WlD7TmBuaGWiOKtE9vNOnTPNiHD5huu-7fdkyOP6cMr.XsAz73y45BUF2LrF3zW-Ig HTTP/1.1" 500 -

```

I couldnt understand this message. Can some one help please. My program is shown below.

```
from flask import Flask
from flask import request

from oic import rndstr
from oic.oic import Client
from oic.utils.http_util import Redirect
from oic.oic.message import AuthorizationResponse
from oic.utils.authn.client import CLIENT_AUTHN_METHOD

from jwkest.jwk import RSAKey

app = Flask(__name__)


client = Client(client_id='*****', client_authn_method=CLIENT_AUTHN_METHOD)


@app.route('/openid-callback')
def redirect_uri():

    response = client.parse_response(
        AuthorizationResponse,
        info=request.query_string,
        sformat="urlencoded"
    )

    args = {
        "code": response["code"],
        "client_secret": "*****",
        "token_endpoint": "*****"
    }

    with open("keycloak.key", "r") as f:
        key = f.read()
        key = RSAKey(kid="*****", use="dec", alg="RS256", key=key)

    resp = client.do_access_token_request(state=response["state"],
                                          request_args=args,
                                          authn_method="client_secret_basic",
                                          key=[key])


@app.route('/openid-login')
def login():

    args = {
        "client_id": client.client_id,
        "response_type": "code",
        "scope": ["openid"],
        "nonce": rndstr(),
        "redirect_uri": "*****",
        "state": rndstr()
    }

    auth_req = client.construct_AuthorizationRequest(request_args=args)
    login_url = auth_req.request('*****')

    return Redirect(login_url)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)

```

**Comment by schlenk** [comment]
This has nothing to do with oic, it is more a usage question for jwkest. So closing this here.

You probably have a key in a format thats not accepable for RSAKey, just look at the helper methods in jkwest that convert keys from DER/PEM to a RSAKey and try those.

You could probably just use the OIDC discovery to find out the proper keys via the jwks URI anyway, so you might be doing too much work too.
