### ISSUE TITLE
provider_config throws mismatch for login.microsoft.com

### ISSUE THREAD

**Issue by przecze** [OpenIDC/pyoidc#743]
Reproduction:
```
>>> from oic import oic
>>> oic.Client().provider_config("https://login.microsoftonline.com/organizations/v2.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/przemek/.local/lib/python3.7/site-packages/oic/oauth2/__init__.py", line 1113, in provider_config
    self.handle_provider_config(pcr, issuer, keys, endpoints)
  File "/home/przemek/.local/lib/python3.7/site-packages/oic/oauth2/__init__.py", line 1063, in handle_provider_config
    % (_issuer, _pcr_issuer)
oic.exception.PyoidcError: provider info issuer mismatch 'https://login.microsoftonline.com/organizations/v2.0' != 'https://login.microsoftonline.com/{tenantid}/v2.0'
```

For reference, check https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration
Is it possible that microsoftonline.com has malformed configuration, or maybe the library is doing to restrictive checks?

**Comment by schlenk** [comment]
MS has a malformed config for the common/org/etc things, its correct for single tenants.

**Comment by schlenk** [comment]
See also https://github.com/OpenIDC/pyoidc/issues/520

**Comment by tpazderka** [comment]
This might also be solvable by using `issuer_mismatch`.
